services:
  app:
    build: .
    ports:
      - "8888:8888"
    container_name: hoangtu-be
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/hoangtusport
      - SPRING_DATASOURCE_USERNAME=hoangtu
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ./upload:/app/upload
    networks:
      - hoangtu-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    container_name: hoangtu-db
    image: mysql:lts
    ports:
      - "3308:3306"
    environment:
      - MYSQL_DATABASE=hoangtusport
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=hoangtu
      - MYSQL_PASSWORD=123456
    volumes:
      - mysql-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - hoangtu-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  hoangtu-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local 