spring:
  application:
    name: hoangtu
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    web:
      pageable:
        one-indexed-parameters: true

# server:
#   port: 8888
#   address: 0.0.0.0

lat:
  jwt:
    base64-secret: ${JWT_SECRET}
    access-token-validity-in-seconds: ${JWT_ACCESS_TOKEN_VALIDITY}
    refresh-token-validity-in-seconds: ${JWT_REFRESH_TOKEN_VALIDITY}
  upload-file:
    base-uri: file:///D:/BackEnd-Java-Learning/upload/

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}

vnpay:
  pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: ${VNPAY_RETURN_URL:http://192.168.1.102:5173/confirmation}
  tmn-code: ${VNPAY_TMN_CODE:YOURCODE}
  hash-secret: ${VNPAY_HASH_SECRET:YOURHASHSECRET}
  api-url: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
  version: 2.1.0
  command: pay
  ip-addr: 127.0.0.1

frontend:
  payment-result-url: ${FRONTEND_PAYMENT_RESULT_URL}
  confirmation-url: ${FRONTEND_CONFIRMATION_URL:http://localhost:3000/confirmation}